### ISSUE TITLE
Cannot access Dashboard after install in WSL2

### ISSUE THREAD

**Issue by BenPashley** [omerbsezer/Fast-Kubeflow#1]
Hi,

Thank you so much for the great repo! It’s really helpful.  I’ve tried installing in WSL2 and I am unable to access the dashboard at http://10.64.140.43.nip.io/ with all containers running including the gateway.  It just times out.  I’ve also got the same issue installing on bare metal.  I’ve seen some other posts with the same issue but no conclusive solution for a Charmed Kubeflow installation. 

Do you have any suggestions?

Ben

**Comment by omerbsezer** [comment]
Hi, 

I pushed to install KF on WSL2 using Juju here: https://github.com/omerbsezer/Fast-Kubeflow/blob/main/Installing-Kubeflow.md 

Please have look there, I also noted some troubleshooting and how to check whether it’s working or not. Your problem could be ingress, I also found solution and defined on that page.

But later, I decided to continue with Vagrant (VM) to use all features of KF. In the main page, you can see how I install it using Vagrant.   

BR
